### DISCUSSION TITLE
Different Controller Assignments for Turtlebot4 lite, Lite launch parameters?

### DISCUSSION THREAD

**Discussion by slowrunner** [turtlebot/turtlebot4#84] [Ideas]
The Turtlebot4 lite launches with the same controller button assignments as the TB4 std, that include assignments not useful for the lite.  The buttons assigned "Select", "Back" perhaps should be assigned "Wall Follow Left" and "Wall Follow Right"?

I am using an inexpensive USB-A dongle connection wireless SNES Gamepad instead of the not-available-for-purchase Bluetooth TurtleBot4 controller.  
![WaLI_SNES_Controller](https://user-images.githubusercontent.com/8950202/204100915-6f86efa3-d5ea-42b1-9005-0844a47f0083.jpg)

I have not yet figured out how to remap the TurtleBot4 controller's "Home" assignment to my SNES "Select" (Button value 8) to issue the /dock and /undock action goals.

Additionally, while the TurtleBot4 documentation states the joy_teleop node is launched, it is if fact only launched in the standard launch.  It would be great if "start_joy_teleop" and perhaps "controller_config" were launch parameters to the lite launch.

My turtlebot4.yaml changes:
```
    # SNES     Button Value    TB4_Controller  Default Assignment   My Assignment
    # X            0                 a            ["Select"]         ["Wall Follow Right"]
    # A            1                 b            ["EStop"]          ["EStop"]
    # B            2                 y            ["RPLIDAR Motor"]  ["RPLIDAR Motor"]
    # Y            3                 x            ["Back"]           ["Wall Follow Left"]Y

    controller:
      a: ["Wall Follow Right"]
      b: ["EStop"]
      x: ["Wall Follow Left"]
      y: ["RPLIDAR Motor"]
```
Here is a video of my WaLI doing wall following commanded from the SNES Gamepad:

https://player.vimeo.com/video/775216697
