### ISSUE TITLE
Automatic docking

### ISSUE THREAD

**Issue by alexswerner** [turtlebot/turtlebot4#12]
Is automatic docking supposed to work? I found a service for it and tried:
```
ubuntu@uwbot-01:~$ ros2 action send_goal /dock irobot_create_msgs/action/DockServo {}
Waiting for an action server to become available...
Sending goal:
     {}

Goal was rejected.
```
That happens when the dock is visible:
```
ubuntu@uwbot-01:~$ ros2 topic echo /dock
header:
  stamp:
    sec: 1657889078
    nanosec: 962197994
  frame_id: ''
dock_visible: true
is_docked: false
```
Please let me know if this is rather an Icreate3 issue.
