### ISSUE TITLE
The standard version of Raspberry Pi is replaced with nx and other SBCs.

### ISSUE THREAD

**Issue by ncnynl** [turtlebot/turtlebot4#278]
**Describe the the feature you would like**
The standard version of Raspberry Pi is replaced with nx and other SBCs.

**Other notes**
I have basically finished switching the standard version from Raspberry Pi 4B to Xavier nx. The same applies to other nano, orin nx, and Xavier.

I have a question here. I found that the pin port for i2c does not use the regular i2c of the Raspberry Pi. The current display on the pcba uses pin7 (GPIO4) and pin29 (GPIO5) of the Raspberry Pi as i2c instead of Using pin3 (SDA) and pin4 (SCL) of Raspberry Pi identity? If this position is used, there is no need to change the wiring, and the original wiring can be used directly.

At the same time, the program also needs to make corresponding pin port correspondences.
```

   gpio:
       user_button_1: 130 # 19 for rpi4, 130 for xaiver nx
       user_button_2: 133 # 16for rpi4, 133 for xaiver nx
       user_button_3: 151 # 26 for rpi4, 151 for xaiver nx
       user_button_4: 129 # 20 for rpi4, 129 for xaiver nx

       led_green_power: 112 # 17 for rpi4, 112 for xaiver nx
       led_green_motors: 127 # 18 for rpi4, 127 for xaiver nx
       led_green_comms: 149 # 27 for rpi4, 149 for xaiver nx
       led_green_wifi: 152 # 24 for rpi4, 152 for xaiver nx
       led_green_battery: 16 # 22 for rpi4, 16 for xaiver nx
       led_red_battery: 153 # 23 for rpi4, 153 for xaiver nx
       led_green_user_1: 150 # 25 for rpi4, 150 for xaiver nx
       led_green_user_2: 106 # 6for rpi4, 106 for xaiver nx
       led_red_user_2: 128 # 21 for rpi4, 128 for xaiver nx

       display_reset: 84 # 13 for rpi4, 84 for xaiver nx

base:
       gpiochip0: 1 # 0 for rpi4, 1 for xaiver nx
       gpiochip1: 2 # 2 for xavier nx
       i2c_bus: 8 #3 for rpi4, 4 for nx
       i2c_device_id: 0x3c #0x3C for rpi4 nx
```

for led_green_battery: 16 # 22 for rpi4, 16 for xaiver nx, is under gpiochip2, the other is under gpiochip1
