### ISSUE TITLE
Turtlebot4 Does Not Move When Given /cmd_vel

### ISSUE THREAD

**Issue by kfu02** [turtlebot/turtlebot4#359]
### Robot Model

Turtlebot4 Standard

### ROS distro

Galactic

### Networking Configuration

Simple Discovery

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

Not sure, whatever was preinstalled on turtlebot when it arrived.

### Type of issue

Other

### Expected behaviour

I have followed the Basic Setup guide and successfully SSH'd into my turtlebot 4. When I try to move the turtlebot with ROS commands e.g. 
```
ros2 topic pub /cmd_vel geometry_msgs/msg/Twist \
"linear:
  x: 0.0
  y: 0.0
  z: 0.0
angular:
  x: 0.0
  y: 0.0
  z: 0.1"
```
the turtlebot should spin in place.

### Actual behaviour

It does not move at all. Echoing the /cmd_vel shows:
```
---
linear:
  x: 0.0
  y: 0.0
  z: 0.0
angular:
  x: 0.0
  y: 0.0
  z: 0.1
---
```
but the turtlebot remains idle.

### To Reproduce

1. Open a brand new Turtlebot
2. Follow Basic Setup to SSH into it
3. Publish a velocity to cmd_vel/
4. Echo cmd_vel/ to confirm it is receiving published messages
