### ISSUE TITLE
LiDAR ranges do not start from angle 0 relative to the robot's heading 

### ISSUE THREAD

**Issue by myamo1** [turtlebot/turtlebot4#390]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

Simple Discovery

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

ros-humble-rplidar-ros

### Type of issue

LIDAR

### Expected behaviour

The first scanner range should be at angle 0 (the heading of turtlebot).

### Actual behaviour

The scanner ranges are not calibrated to start from the angle 0 relative to the x-axis of the robot (its heading) and keep changing.

### To Reproduce

ros2 launch turtlebot4_bringup rplidar.launch.py

**Comment by RustyCPR** [comment]
Hi @myamo1 
Can you please share a screen shot(s) of the concern you are seeing? 
Thanks,
Rusty

**Comment by myamo1** [comment]
[data_scan_pb_tbt4.odt](https://github.com/turtlebot/turtlebot4/files/14924102/data_scan_pb_tbt4.odt)
The attached file is an example where I put a box facing the turtlebot and collect the scanner ranges. The red ranges in the file are the ones associated with the box but are shifted. The first range (i.e., scanner.ranges[0]) should reflect the box. Moreover, at every scan, the order changes; it keeps shifting.

**Comment by RustyCPR** [comment]
Hi @myamo1 
There should be no expectation that the first angle would be at 0 degrees according to the robot's direction. The laser scan message contains the angle min, angle max and angle increment required to be able to properly use the range data from that message.
See details here: https://docs.ros.org/en/api/sensor_msgs/html/msg/LaserScan.html 

Regards,
Rusty

**Comment by myamo1** [comment]
Thanks @RustyCPR
But which frame are the angles given relative to? It should be given relative to the frame attached to the robot. At least, that is how it works in Gazebo. I tried my code there, and it worked. But if the scans are not given in a specific frame, how can we know each scan corresponds to which angle in the global frame or the attached frame to the robot?

**Comment by RustyCPR** [comment]
Hi @myamo1 
The message contains all of the information needed: 
```
header:
  stamp:
    sec: 1713366206
    nanosec: 502688652
  frame_id: rplidar_link
angle_min: -3.1241390705108643
angle_max: 3.1415927410125732
angle_increment: 0.005806980188935995
time_increment: 0.001498553203418851
scan_time: 1.6169389486312866
range_min: 0.15000000596046448
range_max: 12.0
ranges:
- 0.6639999747276306
```
The frame_id is in the header, all angles are relevant to that frame. That is the first part of the message when echo'ed. 
Reviewing the [link](https://docs.ros.org/en/api/sensor_msgs/html/msg/LaserScan.html) I sent yesterday, it also specifies:
 **_angles are measured around the positive Z axis (counterclockwise, if Z is up) with zero angle being forward along the x axis_**
