### ISSUE TITLE
Humble movement command doesn't work

### ISSUE THREAD

**Issue by openminddev** [turtlebot/turtlebot4#512]
### Robot Model

Turtlebot4 Lite

### ROS distro

Humble

### Networking Configuration

Simple Discovery

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

N/A

### Type of issue

Other

### Expected behaviour

I followed the documentation, but the humble command didn't work for driving it and the jazzy command worked.
```
Humble command (didn't work):
ros2 topic pub /cmd_vel geometry_msgs/msg/Twist \
"twist:
  linear:
    x: 0.1
    y: 0.0
    z: 0.0
  angular:
    x: 0.0
    y: 0.0
    z: 0.0"

Jazzy command (worked):
ros2 topic pub /cmd_vel geometry_msgs/msg/TwistStamped \
"twist:
  linear:
    x: 0.1
    y: 0.0
    z: 0.0
  angular:
    x: 0.0
    y: 0.0
    z: 0.0"
```

### Actual behaviour

Both should work

### To Reproduce

I tried both commands
