### ISSUE TITLE
Battery discharging and charging

### ISSUE THREAD

**Issue by simon-hauser** [turtlebot/turtlebot4#64]
Hi,
I wanted to double check with you if the runtime and charging speed I have is within the expectations.

Today I started our TB standard version with 47% charge. It was on for around 25 min, during which I drove maybe 30-40 meters, so the robot was mostly idle. The Lidar was always turning, however I only drove it manually with the joystick. After this, the charge was at 16% and I needed to abort an experiment to charge it again.

The robot then was on the charging dock for almost 3.5 hours and the charge now says 96%.

Is this consistent with runtime and charging speed from your experience? To me it seems that discharging is too fast and charging too slow, but this is of course quite subjective ;).

Thanks for your help,
best,
simon

**Comment by roni-kreinin** [comment]
The robot does seem to be discharging quite quickly. The expected runtime is 2.5-4 hours depending on load, and a full charge typically takes about 2.5 hours. If the robot is under heavy load while charging, it may take more.

Can you take the robot off the dock and echo the `/battery_status` topic? It would be useful to see the current draw while it is idle.

**Comment by simon-hauser** [comment]
Hi,
Thanks for the quick answer.
I needed to wait a couple of seconds after taking the robot off the dock before the `/battery_status` was getting published. I drove maybe 10 m, stopped the robot for 10 seconds, then echoed the status:

```
header:
 stamp:
    sec: 1650546432
    nanosec: 129763746
  frame_id: ''
voltage: 15.217000007629395
temperature: 25.850000381469727
current: -1.121999979019165
charge: 1.7480000257492065
capacity: 2.0490000247955322
design_capacity: 2.0490000247955322
percentage: 0.8500000238418579
power_supply_status: 0
power_supply_health: 0
power_supply_technology: 0
present: true
cell_voltage: []
cell_temperature: []
location: ''
serial_number: ''
---
header:
  stamp:
    sec: 1650546432
    nanosec: 129763746
  frame_id: ''
voltage: 15.217000007629395
temperature: 25.850000381469727
current: -1.121999979019165
charge: 1.7480000257492065
capacity: 2.0490000247955322
design_capacity: 2.0490000247955322
percentage: 0.8500000238418579
power_supply_status: 0
power_supply_health: 0
power_supply_technology: 0
present: true
cell_voltage: []
cell_temperature: []
location: ''
serial_number: `'
---
```

How does this look to you? The robot has no payload on top of the acrylic plate and no additional hardware is connected. Camera is connected and Lidar is turning.

**Comment by simon-hauser** [comment]
When the robot is on the dock, this is the echo `/battery_status`:
```
header:
  stamp:
    sec: 1650546966
    nanosec: 94047288
  frame_id: ''
voltage: 15.753000259399414
temperature: 26.850000381469727
current: 0.27000001072883606
charge: 1.7730000019073486
capacity: 2.0490000247955322
design_capacity: 2.0490000247955322
percentage: 0.8700000047683716
power_supply_status: 0
power_supply_health: 0
power_supply_technology: 0
present: true
cell_voltage: []
cell_temperature: []
location: ''
serial_number: ''
---
```

I could add that when I received the robot, I could not switch it off: the LED ring would blink 3 times but no sound was played and the robot just stayed on. I could solve this issue by resetting the battery and since then booting and shutting down seems to work properly.

**Comment by roni-kreinin** [comment]
The charging current does seem to be fairly low. Typically we want to see about 1A when charging. Can you try a couple of tests to narrow down the issue?

- On the RPi run `sudo systemctl stop turtlebot4`. This will stop the `turtlebot4` service which runs all of the ROS2 nodes. Once the service is stopped, echo `/battery_status` again while the robot is off the dock.
- Unplug the [power adapter board](https://iroboteducation.github.io/create3_docs/hw/adapter/) from the Create 3. This will power off the RPi, PCBA, and lidar/camera. Then echo `/battery_status` with the robot off the dock. You can also try charging with the adapter board disconnected which should give you faster charge time.

**Comment by simon-hauser** [comment]
Sorry for the late reply, I was a couple of days out of office.
Here is the `/battery_status` after running `sudo systemctl stop turtlebot4` while the robot is off the dock. The robot has no payload added:
```
header:
  stamp:
    sec: 1650546335
    nanosec: 745660753
  frame_id: ''
voltage: 15.340999603271484
temperature: 23.850000381469727
current: -0.7680000066757202
charge: 1.7719999551773071
capacity: 2.0490000247955322
design_capacity: 2.0490000247955322
percentage: 0.8600000143051147
power_supply_status: 0
power_supply_health: 0
power_supply_technology: 0
present: true
cell_voltage: []
cell_temperature: []
location: ''
serial_number: ''
```
And this is the echo after unplugging the power adapter board, robot is off the dock:
```
header:
  stamp:
    sec: 1650546565
    nanosec: 805095732
  frame_id: ''
voltage: 15.404999732971191
temperature: 24.549999237060547
current: -0.24699999392032623
charge: 1.7230000495910645
capacity: 2.0490000247955322
design_capacity: 2.0490000247955322
percentage: 0.8399999737739563
power_supply_status: 0
power_supply_health: 0
power_supply_technology: 0
present: true
cell_voltage: []
cell_temperature: []
location: ''
serial_number: ''
```
And lastly the echo of the robot on the dock, adapter board unplugged:
```
header:
  stamp:
    sec: 1650546698
    nanosec: 67249081
  frame_id: ''
voltage: 15.843999862670898
temperature: 24.950000762939453
current: 1.0889999866485596
charge: 1.7269999980926514
capacity: 2.0490000247955322
design_capacity: 2.0490000247955322
percentage: 0.8399999737739563
power_supply_status: 0
power_supply_health: 0
power_supply_technology: 0
present: true
cell_voltage: []
cell_temperature: []
location: ''
serial_number: ''
```
The charging current was increasing over a couple of seconds after putting it on the dock but then stays at over 1A.
